// <auto-generated />
namespace MVC_GIT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_customer_and_order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_customer_and_order));
        
        string IMigrationMetadata.Id
        {
            get { return "202209230514280_add_customer_and_order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
